name: Laravel CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'

  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17

        env:
          POSTGRES_DB: devops_task_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres -d devops_task_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine

        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: pdo, pdo_pgsql
          coverage: none

      - name: Copy environment file
        run: cp .env.example .env

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Run migrations
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: devops_task_test
          DB_USERNAME: postgres
          DB_PASSWORD: secret

          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379

        run: php artisan migrate --force

      - name: Run tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          DB_DATABASE: devops_task_test
          DB_USERNAME: postgres
          DB_PASSWORD: secret

          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379

        run: php artisan test

    build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/sopheaklaing/devops-task-api:${{ github.sha }}

      - name: Tag production image
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull ghcr.io/sopheaklaing/devops-task-api:${{ github.sha }}
          docker tag ghcr.io/sopheaklaing/devops-task-api:${{ github.sha }} ghcr.io/sopheaklaing/devops-task-api:1.0.0
          docker push ghcr.io/sopheaklaing/devops-task-api:1.0.0